/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easysurf.Tela;

import easysurf.Controlador.ControladorAluno;
import easysurf.Controlador.ControladorEscola;
import easysurf.Controlador.ControladorPrincipal;
import easysurf.DAOs.AulaDAO;
import easysurf.Entidade.Aluno;
import easysurf.Entidade.Aula;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caroline
 */
public class TelaAluno extends javax.swing.JFrame {
    
    private static TelaAluno instance;
    private String CPF;
    private Aluno aluno;
    private ArrayList<Aula> aulas;
    
    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
        listener();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAulas = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnNovaAula = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLnivel = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        nomeAluno = new javax.swing.JLabel();
        telefoneAluno = new javax.swing.JLabel();
        labelNomeContato = new javax.swing.JLabel();
        nomeContato = new javax.swing.JLabel();
        labelRelacaoContato = new javax.swing.JLabel();
        relacaoContato = new javax.swing.JLabel();
        labelTelefoneContato = new javax.swing.JLabel();
        telefoneContato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNome.setText("Nome:");

        labelTelefone.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelTelefone.setText("Telefone:");

        tabelaAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Nível", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAulas);

        btnEditar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abreTelaEdicaoAluno(evt);
            }
        });

        btnNovaAula.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnNovaAula.setText("Nova Aula");
        btnNovaAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abreTelaCadastroAula(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Nível:");

        jLnivel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLnivel.setText("1");

        btnVoltar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaParaTelaAnterior(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAluno(evt);
            }
        });

        nomeAluno.setText("jLabel2");

        telefoneAluno.setText("jLabel2");

        labelNomeContato.setText("Nome contato:");

        nomeContato.setText("jLabel4");

        labelRelacaoContato.setText("Relação:");

        relacaoContato.setText("jLabel7");

        labelTelefoneContato.setText("Telefone:");

        telefoneContato.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addGap(18, 18, 18)
                                .addComponent(nomeAluno)
                                .addGap(107, 107, 107)
                                .addComponent(labelTelefone)
                                .addGap(18, 18, 18)
                                .addComponent(telefoneAluno))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnNovaAula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                .addComponent(jLabel5)
                                                .addComponent(jLnivel))
                                            .addGap(26, 26, 26))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNomeContato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeContato))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTelefoneContato)
                                .addGap(41, 41, 41)
                                .addComponent(telefoneContato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(labelRelacaoContato)))
                        .addGap(18, 18, 18)
                        .addComponent(relacaoContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(26, 26, 26)
                        .addComponent(btnNovaAula)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLnivel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefone)
                            .addComponent(labelNome)
                            .addComponent(nomeAluno)
                            .addComponent(telefoneAluno))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeContato)
                    .addComponent(nomeContato))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefoneContato)
                            .addComponent(telefoneContato)
                            .addComponent(labelRelacaoContato)
                            .addComponent(relacaoContato))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abreTelaEdicaoAluno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreTelaEdicaoAluno
        ControladorPrincipal.getInstance().mostraTelaEdicaoAluno(aluno.getCPF());
    }//GEN-LAST:event_abreTelaEdicaoAluno

    private void removeAluno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAluno
       ControladorEscola.getInstance().removeAluno(aluno);
       limpaTela();
    }//GEN-LAST:event_removeAluno

    private void voltaParaTelaAnterior(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaParaTelaAnterior
        limpaTela();
        ControladorPrincipal.getInstance().mostraTelaPrincipal();
    }//GEN-LAST:event_voltaParaTelaAnterior

    private void abreTelaCadastroAula(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreTelaCadastroAula
        ControladorPrincipal.getInstance().mostraTelaCadastroAula(aluno.getCPF());
        loadTable();
    }//GEN-LAST:event_abreTelaCadastroAula

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }
           
    void loadTable() {
        System.out.println(aluno.getCPF());
        String[] colunasAulas = new String[]{"Data", "Nivel", "Status", "ID"};
        DefaultTableModel tableModel = new DefaultTableModel(colunasAulas, 0);
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        for (Aula aula : aulas) {
            Date data = aula.getDataPagamento();
            int nivel = aula.getNivel();
            String feita;
            if(aula.isRealizada()){
                feita = "Realizada";
            }else{
                feita = "Não Realizada";
            }
            int id = aula.getNumeroAula();
            Object[] dataAula = {data, nivel, feita, id};
            tableModel.addRow(dataAula);
            
        }
        tabelaAulas.setModel(tableModel);
    }

    public void listener(){
            tabelaAulas.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    ControladorPrincipal.getInstance().mostraTelaEdicaoAula((int)tabelaAulas.getValueAt(row, 3), aluno);  ///Manter essa linha, pro resto funfarr 
                    loadTable();
                    limpaTela();
                }
            }
        });
    }
    
    public static TelaAluno getInstance() {
        if (instance == null) {
            return instance = new TelaAluno();
        }
        return instance;
    }
    
     public void limpaTela() {
        nomeAluno.setText("");
        telefoneAluno.setText("");
        jLnivel.setText("");      
        nomeContato.setText("");
        telefoneContato.setText("");
        relacaoContato.setText("");
        ControladorPrincipal.getInstance().escondeTelaAluno();
    }
    
     public void iniciaTela(Aluno aluno) {
        this.aluno = aluno;
        this.aulas = aluno.getAulas();
        nomeAluno.setText(aluno.getNome());
        telefoneAluno.setText(aluno.getTelefone());
        jLnivel.setText(String.valueOf(aluno.getNivel()));      
        nomeContato.setText(aluno.getNomeEmergencia());
        telefoneContato.setText(aluno.getTelefoneEmergencia());
        relacaoContato.setText(aluno.getRelacaoEmergencia());
        loadTable();
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovaAula;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLnivel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeContato;
    private javax.swing.JLabel labelRelacaoContato;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTelefoneContato;
    private javax.swing.JLabel nomeAluno;
    private javax.swing.JLabel nomeContato;
    private javax.swing.JLabel relacaoContato;
    private javax.swing.JTable tabelaAulas;
    private javax.swing.JLabel telefoneAluno;
    private javax.swing.JLabel telefoneContato;
    // End of variables declaration//GEN-END:variables
}
